/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideExamInfoPanel: typeof import('./src/components/SideExamInfoPanel.vue')['default']
    SideExamsPanel: typeof import('./src/components/SideExamsPanel.vue')['default']
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLink: typeof import('tdesign-vue-next')['Link']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
  }
}
